version: "3.9"
services:
  game_ts:
    build: .
    container_name: game_ts
    ports:
      - "5000:5000"
    depends_on:
      - game_nginx_ts
      - game_psql_ts

  game_nginx_ts:
    image: nginx
    container_name: game_nginx_ts
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"

    restart: unless-stopped

  game_psql_ts:
    image: postgres
    container_name: game_psql_ts
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "docker" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
        POSTGRES_HOST : ${PG_HOST:-game_psql_ts}
        POSTGRES_USER: ${PG_USER:-docker}
        POSTGRES_PASSWORD: ${PG_PASSWORD:-password}
        POSTGRES_DB: ${PG_DB:-rock_paper_scissors}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/init.sql
