version: "3.9"
services:
  game_ts:
    build: .
    container_name: game_ts
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - game_psql_ts

  game_psql_ts:
    build: ./docker/
    container_name: game_psql_ts
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: ${PG_USER:-docker}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-password}
      POSTGRES_DB: ${PG_DB:-rock_paper_scissors}