version: "3.9"
services:
  game_ts:
    build: .
    container_name: game_ts
    ports:
      - "5000:5000"
    depends_on:
      - nginx_ts
      - psql_ts

  nginx_ts:
    image: nginx
    container_name: nginx_ts
    volumes:
      - .congif/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"

    restart: unless-stopped

  psql_ts:
    image: postgres
    container_name: psql_ts
